### PR TITLE
Update CI tests

### PR DESCRIPTION
**Pull request by devmotion**
Run CI tests on Julia LTS, stable, and master.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This library probably needs quite a bit of updates. I've been waiting on getting it updated before adding it to the main docs, and adding regression tests to it.

**Comment by devmotion** [comment]
We should disable the tests on travis-ci.org, it seems currently they run both on travis-ci.com and travis-ci.org.

**Comment by devmotion** [comment]
Hmm seems tests on Travis run with DiffEqBase 6.20 whereas locally tests passed with DiffEqBase 6.29. Maybe we should just lower bounding DiffEqBase?

**Comment by ChrisRackauckas** [comment]
Yes, that should help. Note that I think callbacks will be broken for sure, and they aren't tested.

**Comment by devmotion** [comment]
Ah I just noticed, the problem is StochasticDiffEq. Tests fail with version 6.17 but it is the latest version that is compatible with Julia < 1.2. Should we just drop support for Julia < 1.2 in StochasticDelayDiffEq?

**Comment by ChrisRackauckas** [comment]
Yes, just up it to at least v1.3.

**Comment by devmotion** [comment]
OK, I guess this is good to go, tests pass now on Julia 1.4 and master. I'd suggest creating separate PRs for adding more tests and fixing bugs. Can you disable the tests on travis-ci.org? I don't have any permissions for StochasticDelayDiffEq it seems.

**Pull request merged**
